"""Add user relationship to Post

Revision ID: ac2f2724bd48
Revises: 030c4c2d4eea
Create Date: 2026-01-28 17:03:49.331408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2f2724bd48'
down_revision = '030c4c2d4eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('posted',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_user_id_users'), type_='foreignkey')
        batch_op.alter_column('posted',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
